-- AlterTable
ALTER TABLE "Medication" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Medication" ADD COLUMN "endDate" TIMESTAMP(3);
ALTER TABLE "Medication" ADD COLUMN "notes" TEXT;
ALTER TABLE "Medication" ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Medication" ADD COLUMN "times" JSONB;
ALTER TABLE "Medication" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;